In [1]:
import numpy as np

**Yêu cầu 1: Đọc hospital_A.csv và hospital_B.csv.** 

In [2]:
# Đọc file csv hospital_a.csv : 
hospital_a = []
with open('hospital_a.csv', 'r') as file_a:
    for line in file_a:
        hospital_a.append(line.strip().split(','))



np_hospital_a = np.array(hospital_a)
print('Danh sách file hospital_a: ','\n')
print(np_hospital_a)


Danh sách file hospital_a:  

[['age' 'blood_pressure' 'cholesterol' 'heart_risk']
 ['51' '148' '165' '1']
 ['82' '98' '285' '1']
 ['70' '105' '226' '1']
 ['63' '171' '274' '1']
 ['39' '145' '198' '1']
 ['39' '91' '330' '1']
 ['33' '99' '208' '0']
 ['78' '150' '152' '1']
 ['63' '90' '286' '1']
 ['69' '104' '164' '0']
 ['31' '194' '198' '0']
 ['83' '152' '293' '1']
 ['76' '149' '293' '1']
 ['42' '110' '236' '1']
 ['40' '154' '245' '1']
 ['40' '111' '217' '0']
 ['47' '119' '194' '0']
 ['59' '157' '199' '1']
 ['54' '148' '251' '1']
 ['46' '166' '263' '1']
 ['64' '149' '269' '1']
 ['38' '141' '268' '1']
 ['46' '98' '164' '0']
 ['50' '123' '224' '1']
 ['55' '114' '159' '0']
 ['73' '207' '232' '1']
 ['41' '178' '216' '1']
 ['58' '125' '283' '1']
 ['63' '170' '203' '1']
 ['33' '147' '168' '1']
 ['63' '162' '171' '1']
 ['39' '135' '264' '1']
 ['34' '142' '243' '1']
 ['82' '134' '165' '0']
 ['83' '108' '163' '0']
 ['74' '155' '255' '1']
 ['47' '115' '161' '0']
 ['35' '92' '273' '1']
 ['68' '148

In [3]:
# Đọc file hospital_b.csv: 
hospital_b = []
with open('hospital_b.csv', 'r') as file_b: 
    for line in file_b: 
        hospital_b.append(line.strip().split(','))
np_hospital_b = np.array(hospital_b)
print('Danh sách file hospital_b: ','\n')
print(np_hospital_b)

Danh sách file hospital_b:  

[['age' 'blood_pressure' 'cholesterol' 'heart_risk']
 ['55' '172' '203' '1']
 ['41' '143' '258' '1']
 ['50' '126' '195' '0']
 ['58' '132' '235' '1']
 ['68' '175' '221' '1']
 ['32' '104' '250' '1']
 ['74' '143' '291' '1']
 ['65' '136' '260' '1']
 ['34' '145' '349' '1']
 ['78' '92' '155' '0']
 ['81' '168' '189' '1']
 ['33' '174' '239' '1']
 ['45' '141' '158' '1']
 ['74' '153' '224' '1']
 ['71' '173' '240' '1']
 ['40' '195' '200' '1']
 ['42' '104' '266' '1']
 ['50' '142' '166' '1']
 ['57' '145' '161' '1']
 ['64' '128' '259' '1']
 ['50' '156' '368' '1']
 ['55' '174' '253' '1']
 ['71' '173' '215' '1']
 ['32' '131' '187' '0']
 ['44' '100' '273' '1']
 ['69' '179' '270' '1']
 ['79' '166' '254' '1']
 ['58' '101' '191' '0']
 ['59' '173' '239' '1']
 ['36' '168' '204' '1']
 ['55' '213' '164' '0']
 ['59' '143' '288' '1']
 ['43' '126' '171' '0']
 ['45' '95' '293' '1']
 ['51' '120' '217' '0']
 ['31' '162' '178' '1']
 ['48' '90' '231' '1']
 ['42' '120' '281' '1']
 ['48' '

**Yếu cầu 2: Tách từng chỉ số thành các mảng riêng.**

- Tách thành từng mảng riêng ở hospital_a: 

In [4]:
# Tách thành từng mảng riêng ở hospital_a: 
arr_age_a = np.array(np_hospital_a[:,0],)
arr_blood_pre_a = np.array(np_hospital_a[:,1])
arr_cholesterol_a = np.array(np_hospital_a[:,2])
arr_heart_risk_a = np.array(np_hospital_a[:,3])

print('Các mảng được tách ra theo tùng chỉ số: ')


Các mảng được tách ra theo tùng chỉ số: 


In [5]:

print('Mảng Age: ','\n')
print(arr_age_a)

Mảng Age:  

['age' '51' '82' '70' '63' '39' '39' '33' '78' '63' '69' '31' '83' '76'
 '42' '40' '40' '47' '59' '54' '46' '64' '38' '46' '50' '55' '73' '41'
 '58' '63' '33' '63' '39' '34' '82' '83' '74' '47' '35' '68' '54' '37'
 '57' '32' '80' '44' '66' '47' '59' '60' '40' '83' '73' '82' '79' '63'
 '81' '35' '41' '32' '48' '51' '45' '76' '50' '45' '60' '38' '74' '34'
 '84' '72' '41' '30' '75' '69' '70' '72' '34' '50' '36' '77' '64' '48'
 '33' '47' '48' '70' '65' '79' '56' '37' '69' '72' '61' '72' '57' '59'
 '54' '31' '36' '32' '65' '47' '58' '80' '44' '53' '72' '43' '34' '46'
 '39' '81' '74' '65' '78' '74' '40' '79' '60' '74' '79' '47' '36' '43'
 '53' '75' '77' '30' '58' '53' '42' '37' '49' '82' '48' '59' '69' '50'
 '83' '83' '44' '57' '47' '46' '32' '64' '58' '33' '45' '80' '43' '38'
 '57' '84' '43' '67' '72' '43' '70' '50' '65' '65' '59' '35' '76' '48'
 '40' '32' '62' '67' '31' '58' '42' '65' '40' '68' '51' '82' '38' '49'
 '36' '81' '78' '44' '66' '75' '61' '59' '43' '35' '79' '80' '6

In [6]:
print('Mảng Bool_pre: ','\n')
print(arr_blood_pre_a)

Mảng Bool_pre:  

['blood_pressure' '148' '98' '105' '171' '145' '91' '99' '150' '90' '104'
 '194' '152' '149' '110' '154' '111' '119' '157' '148' '166' '149' '141'
 '98' '123' '114' '207' '178' '125' '170' '147' '162' '135' '142' '134'
 '108' '155' '115' '92' '148' '106' '175' '176' '172' '123' '91' '174'
 '129' '177' '177' '167' '217' '125' '167' '119' '105' '140' '174' '153'
 '141' '99' '145' '179' '103' '137' '169' '157' '153' '153' '122' '116'
 '163' '163' '168' '172' '136' '135' '162' '148' '153' '162' '170' '120'
 '124' '98' '142' '93' '132' '139' '116' '143' '93' '93' '164' '122' '101'
 '137' '159' '109' '146' '98' '95' '138' '139' '147' '155' '178' '136'
 '119' '162' '114' '130' '97' '92' '177' '165' '153' '127' '106' '104'
 '113' '211' '154' '149' '115' '176' '156' '140' '145' '128' '112' '122'
 '158' '91' '100' '94' '94' '167' '153' '133' '99' '134' '133' '106' '129'
 '126' '145' '147' '94' '124' '146' '135' '167' '149' '105' '96' '148'
 '92' '143' '175' '142' '125' '148' '1

In [7]:
print('Mảng Choleterol: ','\n')
print(arr_cholesterol_a)

Mảng Choleterol:  

['cholesterol' '165' '285' '226' '274' '198' '330' '208' '152' '286' '164'
 '198' '293' '293' '236' '245' '217' '194' '199' '251' '263' '269' '268'
 '164' '224' '159' '232' '216' '283' '203' '168' '171' '264' '243' '165'
 '163' '255' '161' '273' '256' '162' '379' '298' '206' '206' '272' '292'
 '298' '263' '206' '163' '267' '234' '214' '286' '167' '224' '152' '220'
 '158' '168' '168' '247' '262' '238' '294' '206' '193' '280' '184' '294'
 '152' '295' '156' '284' '229' '299' '161' '233' '295' '228' '244' '254'
 '218' '244' '238' '285' '157' '192' '293' '284' '310' '243' '192' '178'
 '220' '203' '238' '162' '296' '298' '255' '230' '196' '272' '253' '174'
 '287' '273' '292' '259' '242' '213' '290' '280' '157' '154' '206' '272'
 '298' '173' '239' '207' '295' '276' '276' '220' '212' '191' '158' '280'
 '272' '300' '299' '233' '265' '292' '277' '187' '218' '169' '293' '241'
 '184' '251' '243' '204' '167' '251' '228' '266' '314' '278' '233' '234'
 '281' '211' '170' '154' '263

In [8]:
print('Mảng Heart_risk: ','\n')
print(arr_heart_risk_a)

Mảng Heart_risk:  

['heart_risk' '1' '1' '1' '1' '1' '1' '0' '1' '1' '0' '0' '1' '1' '1' '1'
 '0' '0' '1' '1' '1' '1' '1' '0' '1' '0' '1' '1' '1' '1' '1' '1' '1' '1'
 '0' '0' '1' '0' '1' '1' '0' '1' '1' '1' '0' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '0' '1' '1' '1' '1' '0' '1' '1' '1' '1' '1' '1' '1' '1' '0'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '0' '1' '1' '1' '0'
 '0' '1' '1' '0' '1' '1' '0' '0' '0' '1' '0' '1' '1' '1' '1' '0' '1' '1'
 '1' '1' '1' '1' '1' '1' '0' '1' '1' '1' '1' '0' '1' '1' '0' '1' '1' '1'
 '1' '1' '1' '0' '1' '0' '1' '1' '1' '1' '1' '1' '1' '1' '1' '0' '0' '1'
 '1' '0' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '0' '1' '1'
 '1' '1' '1' '0' '0' '1' '1' '1' '1' '1' '0' '1' '1' '0' '1' '1' '1' '1'
 '1' '1' '0' '0' '1' '1' '1' '1' '1' '0' '0' '1' '1' '1' '1' '0' '1' '1'
 '1' '1' '0' '1' '1']


- Tách thành từng mảng riêng ở hospital_b: 

In [9]:
# Tách thành từng mảng riêng ở hospital_b: 
arr_age_b = np.array(np_hospital_b[:,0],)
arr_blood_pre_b = np.array(np_hospital_b[:,1])
arr_cholesterol_b = np.array(np_hospital_b[:,2])
arr_heart_risk_b = np.array(np_hospital_b[:,3])

print('Các mảng được tách ra theo tùng chỉ số: ')


Các mảng được tách ra theo tùng chỉ số: 


In [10]:
print('Mảng Age: ','\n')
print(arr_age_b)

Mảng Age:  

['age' '55' '41' '50' '58' '68' '32' '74' '65' '34' '78' '81' '33' '45'
 '74' '71' '40' '42' '50' '57' '64' '50' '55' '71' '32' '44' '69' '79'
 '58' '59' '36' '55' '59' '43' '45' '51' '31' '48' '42' '48' '37' '79'
 '63' '67' '73' '57' '35' '60' '62' '71' '54' '37' '46' '50' '66' '61'
 '50' '84' '63' '43' '36' '38' '44' '39' '40' '46' '40' '79' '34' '59'
 '53' '84' '36' '52' '83' '78' '75' '44' '39' '67' '81' '61' '61' '45'
 '72' '40' '48' '53' '58' '43' '36' '64' '46' '62' '38' '56' '59' '33'
 '49' '37' '33' '84' '48' '75' '44' '67' '72' '63' '56' '53' '49' '81'
 '76' '83' '37' '70' '82' '40' '34' '71' '62' '76' '38' '74' '41' '39'
 '39' '75' '67' '59' '50' '78' '52' '75' '54' '51' '55' '47' '71' '58'
 '43' '79' '51' '60' '80' '64' '36' '82' '65' '48' '38' '74' '64' '59'
 '79' '73' '38' '47' '44' '71' '32' '61' '72' '78' '49' '75' '36' '77'
 '37' '52' '74' '38' '43' '70' '70' '65' '68' '60' '44' '49' '40']


In [11]:
print('Mảng Bool_pre: ','\n')
print(arr_blood_pre_b)

Mảng Bool_pre:  

['blood_pressure' '172' '143' '126' '132' '175' '104' '143' '136' '145'
 '92' '168' '174' '141' '153' '173' '195' '104' '142' '145' '128' '156'
 '174' '173' '131' '100' '179' '166' '101' '173' '168' '213' '143' '126'
 '95' '120' '162' '90' '120' '126' '138' '173' '121' '121' '156' '131'
 '110' '131' '103' '106' '135' '128' '172' '123' '142' '147' '91' '150'
 '106' '176' '103' '127' '98' '180' '135' '144' '96' '157' '109' '171'
 '108' '107' '93' '132' '141' '96' '208' '131' '137' '130' '126' '140'
 '104' '106' '168' '175' '124' '114' '148' '127' '92' '104' '154' '149'
 '92' '110' '111' '150' '92' '99' '162' '106' '149' '111' '99' '112' '155'
 '167' '165' '126' '150' '108' '116' '171' '91' '98' '109' '92' '106'
 '142' '128' '170' '164' '121' '113' '124' '143' '114' '146' '127' '140'
 '129' '117' '175' '159' '103' '168' '134' '171' '162' '128' '92' '114'
 '139' '147' '113' '103' '165' '179' '137' '105' '115' '92' '172' '101'
 '142' '115' '140' '149' '165' '109' '91' '102

In [12]:
print('Mảng Choleterol: ','\n')
print(arr_cholesterol_b)

Mảng Choleterol:  

['cholesterol' '203' '258' '195' '235' '221' '250' '291' '260' '349' '155'
 '189' '239' '158' '224' '240' '200' '266' '166' '161' '259' '368' '253'
 '215' '187' '273' '270' '254' '191' '239' '204' '164' '288' '171' '293'
 '217' '178' '231' '281' '260' '271' '249' '254' '277' '187' '223' '183'
 '298' '292' '156' '256' '289' '177' '235' '287' '155' '255' '195' '289'
 '296' '292' '221' '279' '277' '198' '274' '156' '239' '185' '168' '162'
 '254' '201' '259' '160' '197' '231' '269' '198' '244' '283' '242' '185'
 '154' '281' '153' '281' '229' '291' '270' '300' '203' '265' '210' '222'
 '244' '281' '298' '265' '213' '213' '368' '186' '167' '203' '193' '194'
 '185' '156' '153' '298' '214' '208' '252' '183' '292' '268' '163' '213'
 '282' '292' '220' '242' '175' '299' '185' '291' '247' '241' '227' '185'
 '176' '183' '178' '267' '203' '159' '295' '283' '289' '299' '176' '209'
 '264' '254' '173' '272' '184' '184' '231' '239' '237' '164' '282' '190'
 '169' '283' '293' '279' '271

In [13]:
print('Mảng Heart_risk: ','\n')
print(arr_heart_risk_b)

Mảng Heart_risk:  

['heart_risk' '1' '1' '0' '1' '1' '1' '1' '1' '1' '0' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '0' '1' '1' '1' '0' '1' '1' '0' '1' '0'
 '1' '0' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '0' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '0' '1' '0' '1' '0' '1'
 '0' '1' '0' '1' '1' '0' '1' '1' '0' '1' '1' '1' '0' '0' '1' '1' '1' '1'
 '1' '1' '1' '0' '1' '1' '1' '1' '1' '1' '1' '0' '1' '1' '1' '0' '0' '0'
 '1' '1' '1' '0' '1' '0' '0' '1' '0' '1' '1' '0' '0' '1' '1' '1' '1' '0'
 '1' '0' '1' '1' '1' '1' '0' '0' '0' '1' '1' '0' '1' '1' '1' '1' '1' '0'
 '0' '1' '1' '0' '1' '1' '1' '1' '1' '1' '0' '1' '0' '1' '1' '1' '1' '1'
 '1' '1' '0' '1' '1' '1' '1' '1' '0' '1' '1' '0' '1' '1' '1' '1' '1' '1'
 '1' '1' '0']


**Yêu cầu 3: Kiểm tra dtype, shape, in 5 dòng đầu/cuối.**

- Hospital_a: 

In [14]:
# Kiểm tra kiểu dữ liệu: 
print(f'Kiểu dữ liệu: {np_hospital_a.dtype}','\n')

# Kiểm tra kích thước chủa dư liệu: 
print(f'Kích thước kiểu dữ liệu là: {np_hospital_a.shape}','\n')

# In 5 dòng đầu của mảng dữ liệu: 
np_5_first_hospital_a = np_hospital_a[1:6,:]
print('In 5 dòng đầu của mảng dữ liệu: ','\n')
print(np_5_first_hospital_a,'\n')

# In 5 dòng cuối của mảng dữ liệu: 
np_5_finall_hospital_a = np_hospital_a[-5:,:]
print('In 5 dòng cuối của mảng dữ liệu:','\n')
print(np_5_finall_hospital_a)

Kiểu dữ liệu: <U14 

Kích thước kiểu dữ liệu là: (201, 4) 

In 5 dòng đầu của mảng dữ liệu:  

[['51' '148' '165' '1']
 ['82' '98' '285' '1']
 ['70' '105' '226' '1']
 ['63' '171' '274' '1']
 ['39' '145' '198' '1']] 

In 5 dòng cuối của mảng dữ liệu: 

[['49' '174' '221' '1']
 ['70' '167' '250' '1']
 ['79' '129' '176' '0']
 ['79' '158' '179' '1']
 ['73' '158' '156' '1']]


- Hospital_b: 


In [15]:
# Kiểm tra kiểu dữ liệu: 
print(f'Kiểu dữ liệu: {np_hospital_b.dtype}','\n')

# Kiểm tra kích thước chủa dư liệu: 
print(f'Kích thước kiểu dữ liệu là: {np_hospital_b.shape}','\n')

# In 5 dòng đầu của mảng dữ liệu: 
np_5_first_hospital_b = np_hospital_b[1:6,:]
print('In 5 dòng đầu của mảng dữ liệu: ','\n')
print(np_5_first_hospital_b,'\n')

# In 5 dòng cuối của mảng dữ liệu: 
np_5_finall_hospital_b = np_hospital_b[-5:,:]
print('In 5 dòng cuối của mảng dữ liệu:','\n')
print(np_5_finall_hospital_b)

Kiểu dữ liệu: <U14 

Kích thước kiểu dữ liệu là: (181, 4) 

In 5 dòng đầu của mảng dữ liệu:  

[['55' '172' '203' '1']
 ['41' '143' '258' '1']
 ['50' '126' '195' '0']
 ['58' '132' '235' '1']
 ['68' '175' '221' '1']] 

In 5 dòng cuối của mảng dữ liệu: 

[['68' '97' '274' '1']
 ['60' '144' '202' '1']
 ['44' '112' '252' '1']
 ['49' '125' '235' '1']
 ['40' '116' '190' '0']]


**Yêu cầu 4: Slicing, lấy 50 bệnh nhân đầu, giữa, cuối.** 

- Hospital_a: 

In [16]:
# Lấy 50 bệnh nhân đầu: 
arr_50_first_hospital_a = np_hospital_a[:51,:51]
print('Lấy 50 bệnh nhân đầu tiên của mảng sữ liệu: ','\n')
print(arr_50_first_hospital_a,'\n')




Lấy 50 bệnh nhân đầu tiên của mảng sữ liệu:  

[['age' 'blood_pressure' 'cholesterol' 'heart_risk']
 ['51' '148' '165' '1']
 ['82' '98' '285' '1']
 ['70' '105' '226' '1']
 ['63' '171' '274' '1']
 ['39' '145' '198' '1']
 ['39' '91' '330' '1']
 ['33' '99' '208' '0']
 ['78' '150' '152' '1']
 ['63' '90' '286' '1']
 ['69' '104' '164' '0']
 ['31' '194' '198' '0']
 ['83' '152' '293' '1']
 ['76' '149' '293' '1']
 ['42' '110' '236' '1']
 ['40' '154' '245' '1']
 ['40' '111' '217' '0']
 ['47' '119' '194' '0']
 ['59' '157' '199' '1']
 ['54' '148' '251' '1']
 ['46' '166' '263' '1']
 ['64' '149' '269' '1']
 ['38' '141' '268' '1']
 ['46' '98' '164' '0']
 ['50' '123' '224' '1']
 ['55' '114' '159' '0']
 ['73' '207' '232' '1']
 ['41' '178' '216' '1']
 ['58' '125' '283' '1']
 ['63' '170' '203' '1']
 ['33' '147' '168' '1']
 ['63' '162' '171' '1']
 ['39' '135' '264' '1']
 ['34' '142' '243' '1']
 ['82' '134' '165' '0']
 ['83' '108' '163' '0']
 ['74' '155' '255' '1']
 ['47' '115' '161' '0']
 ['35' '92' '273'

In [17]:
# Lấy 50 bệnh nhân ở giữa: 
a = np_hospital_a[:len(np_hospital_a)//2,:]
b = np_hospital_a[-len(np_hospital_a)//2:,:]

a_25 = a[-25:,:]
b_25 = b[:25,:]
arr_50_mid_hospital_a = np.concatenate([a_25,b_25])
print('Lấy 50 bệnh nhân ở giữa của mảng dữ liệu: ','\n')
print(arr_50_mid_hospital_a)





Lấy 50 bệnh nhân ở giữa của mảng dữ liệu:  

[['69' '136' '229' '1']
 ['70' '135' '299' '1']
 ['72' '162' '161' '1']
 ['34' '148' '233' '1']
 ['50' '153' '295' '1']
 ['36' '162' '228' '1']
 ['77' '170' '244' '1']
 ['64' '120' '254' '1']
 ['48' '124' '218' '0']
 ['33' '98' '244' '1']
 ['47' '142' '238' '1']
 ['48' '93' '285' '1']
 ['70' '132' '157' '0']
 ['65' '139' '192' '0']
 ['79' '116' '293' '1']
 ['56' '143' '284' '1']
 ['37' '93' '310' '0']
 ['69' '93' '243' '1']
 ['72' '164' '192' '1']
 ['61' '122' '178' '0']
 ['72' '101' '220' '0']
 ['57' '137' '203' '0']
 ['59' '159' '238' '1']
 ['54' '109' '162' '0']
 ['31' '146' '296' '1']
 ['36' '98' '298' '1']
 ['32' '95' '255' '1']
 ['65' '138' '230' '1']
 ['47' '139' '196' '0']
 ['58' '147' '272' '1']
 ['80' '155' '253' '1']
 ['44' '178' '174' '1']
 ['53' '136' '287' '1']
 ['72' '119' '273' '1']
 ['43' '162' '292' '1']
 ['34' '114' '259' '1']
 ['46' '130' '242' '1']
 ['39' '97' '213' '0']
 ['81' '92' '290' '1']
 ['74' '177' '280' '1']
 ['

In [18]:
# Lấy 50 bệnh nhân ở cuối của mảng dữ liệu: 
arr_50_finall_hospital_a = np_hospital_a[-50:,:]
print('Lấy 50 bệnh nhân ở cuối của mảng dữ liệu: ','\n')
print(arr_50_finall_hospital_a)
len(arr_50_finall_hospital_a)

Lấy 50 bệnh nhân ở cuối của mảng dữ liệu:  

[['80' '135' '314' '1']
 ['43' '167' '278' '1']
 ['38' '149' '233' '1']
 ['57' '105' '234' '1']
 ['84' '96' '281' '1']
 ['43' '148' '211' '1']
 ['67' '92' '170' '0']
 ['72' '143' '154' '1']
 ['43' '175' '263' '1']
 ['70' '142' '243' '1']
 ['50' '125' '256' '1']
 ['65' '148' '182' '1']
 ['65' '131' '170' '0']
 ['59' '139' '152' '0']
 ['35' '175' '203' '1']
 ['76' '125' '238' '1']
 ['48' '177' '209' '1']
 ['40' '171' '216' '1']
 ['32' '108' '286' '1']
 ['62' '96' '202' '0']
 ['67' '99' '227' '1']
 ['31' '92' '268' '1']
 ['58' '98' '209' '0']
 ['42' '151' '243' '1']
 ['65' '96' '279' '1']
 ['40' '119' '292' '1']
 ['68' '166' '172' '1']
 ['51' '92' '289' '1']
 ['82' '163' '224' '1']
 ['38' '115' '189' '0']
 ['49' '101' '219' '0']
 ['36' '153' '297' '1']
 ['81' '147' '224' '1']
 ['78' '169' '199' '1']
 ['44' '156' '245' '1']
 ['66' '162' '186' '1']
 ['75' '115' '161' '0']
 ['61' '106' '169' '0']
 ['59' '158' '169' '1']
 ['43' '163' '173' '1']
 ['

50

- Hospital_b: 

In [19]:
# Lấy 50 bệnh nhân đầu: 
arr_50_first_hospital_b = np_hospital_b[:51,:51]
print('Lấy 50 bệnh nhân đầu tiên của mảng sữ liệu: ','\n')
print(arr_50_first_hospital_b,'\n')



Lấy 50 bệnh nhân đầu tiên của mảng sữ liệu:  

[['age' 'blood_pressure' 'cholesterol' 'heart_risk']
 ['55' '172' '203' '1']
 ['41' '143' '258' '1']
 ['50' '126' '195' '0']
 ['58' '132' '235' '1']
 ['68' '175' '221' '1']
 ['32' '104' '250' '1']
 ['74' '143' '291' '1']
 ['65' '136' '260' '1']
 ['34' '145' '349' '1']
 ['78' '92' '155' '0']
 ['81' '168' '189' '1']
 ['33' '174' '239' '1']
 ['45' '141' '158' '1']
 ['74' '153' '224' '1']
 ['71' '173' '240' '1']
 ['40' '195' '200' '1']
 ['42' '104' '266' '1']
 ['50' '142' '166' '1']
 ['57' '145' '161' '1']
 ['64' '128' '259' '1']
 ['50' '156' '368' '1']
 ['55' '174' '253' '1']
 ['71' '173' '215' '1']
 ['32' '131' '187' '0']
 ['44' '100' '273' '1']
 ['69' '179' '270' '1']
 ['79' '166' '254' '1']
 ['58' '101' '191' '0']
 ['59' '173' '239' '1']
 ['36' '168' '204' '1']
 ['55' '213' '164' '0']
 ['59' '143' '288' '1']
 ['43' '126' '171' '0']
 ['45' '95' '293' '1']
 ['51' '120' '217' '0']
 ['31' '162' '178' '1']
 ['48' '90' '231' '1']
 ['42' '120' '2

In [20]:
# Lấy 50 bệnh nhân ở giữa: 
c = np_hospital_b[:len(np_hospital_b)//2,:]
d = np_hospital_b[-len(np_hospital_b)//2:,:]

c_25 = c[-25:,:]
d_25 = d[:25,:]
arr_50_mid_hospital_b = np.concatenate([c_25,d_25])
print('Lấy 50 bệnh nhân ở giữa của mảng dữ liệu: ','\n')
print(arr_50_mid_hospital_b)


Lấy 50 bệnh nhân ở giữa của mảng dữ liệu:  

[['46' '144' '274' '1']
 ['40' '96' '156' '0']
 ['79' '157' '239' '1']
 ['34' '109' '185' '0']
 ['59' '171' '168' '1']
 ['53' '108' '162' '0']
 ['84' '107' '254' '1']
 ['36' '93' '201' '0']
 ['52' '132' '259' '1']
 ['83' '141' '160' '1']
 ['78' '96' '197' '0']
 ['75' '208' '231' '1']
 ['44' '131' '269' '1']
 ['39' '137' '198' '0']
 ['67' '130' '244' '1']
 ['81' '126' '283' '1']
 ['61' '140' '242' '1']
 ['61' '104' '185' '0']
 ['45' '106' '154' '0']
 ['72' '168' '281' '1']
 ['40' '175' '153' '1']
 ['48' '124' '281' '1']
 ['53' '114' '229' '1']
 ['58' '148' '291' '1']
 ['43' '127' '270' '1']
 ['36' '92' '300' '1']
 ['64' '104' '203' '0']
 ['46' '154' '265' '1']
 ['62' '149' '210' '1']
 ['38' '92' '222' '1']
 ['56' '110' '244' '1']
 ['59' '111' '281' '1']
 ['33' '150' '298' '1']
 ['49' '92' '265' '1']
 ['37' '99' '213' '0']
 ['33' '162' '213' '1']
 ['84' '106' '368' '1']
 ['48' '149' '186' '1']
 ['75' '111' '167' '0']
 ['44' '99' '203' '0']
 ['

In [21]:
# Lấy 50 bệnh nhân ở cuối của mảng dữ liệu: 
arr_50_finall_hospital_b = np_hospital_b[-50:,:]
print('Lấy 50 bệnh nhân ở cuối của mảng dữ liệu: ','\n')
print(arr_50_finall_hospital_b)


Lấy 50 bệnh nhân ở cuối của mảng dữ liệu:  

[['78' '129' '176' '0']
 ['52' '117' '183' '0']
 ['75' '175' '178' '1']
 ['54' '159' '267' '1']
 ['51' '103' '203' '0']
 ['55' '168' '159' '1']
 ['47' '134' '295' '1']
 ['71' '171' '283' '1']
 ['58' '162' '289' '1']
 ['43' '128' '299' '1']
 ['79' '92' '176' '0']
 ['51' '114' '209' '0']
 ['60' '139' '264' '1']
 ['80' '147' '254' '1']
 ['64' '113' '173' '0']
 ['36' '103' '272' '1']
 ['82' '165' '184' '1']
 ['65' '179' '184' '1']
 ['48' '137' '231' '1']
 ['38' '105' '239' '1']
 ['74' '115' '237' '1']
 ['64' '92' '164' '0']
 ['59' '172' '282' '1']
 ['79' '101' '190' '0']
 ['73' '142' '169' '1']
 ['38' '115' '283' '1']
 ['47' '140' '293' '1']
 ['44' '149' '279' '1']
 ['71' '165' '271' '1']
 ['32' '109' '248' '1']
 ['61' '91' '233' '1']
 ['72' '102' '163' '0']
 ['78' '171' '211' '1']
 ['49' '169' '206' '1']
 ['75' '144' '189' '1']
 ['36' '144' '259' '1']
 ['77' '150' '224' '1']
 ['37' '106' '162' '0']
 ['52' '172' '183' '1']
 ['74' '128' '252' '1'

**Yêu cầu 5: Mask: bệnh nhân có huyết áp > 140 hoặc cholesterol > 240.**

- Hospital_a: 

In [22]:
# Bệnh nhân có huyết > 140 :
mask_blood_pre_a = np_hospital_a[1:,1].astype(int) > 140

print('Bệnh nhân có huyết áp > 140: ','\n')
print(np_hospital_a[1:,:][mask_blood_pre_a])
 

Bệnh nhân có huyết áp > 140:  

[['51' '148' '165' '1']
 ['63' '171' '274' '1']
 ['39' '145' '198' '1']
 ['78' '150' '152' '1']
 ['31' '194' '198' '0']
 ['83' '152' '293' '1']
 ['76' '149' '293' '1']
 ['40' '154' '245' '1']
 ['59' '157' '199' '1']
 ['54' '148' '251' '1']
 ['46' '166' '263' '1']
 ['64' '149' '269' '1']
 ['38' '141' '268' '1']
 ['73' '207' '232' '1']
 ['41' '178' '216' '1']
 ['63' '170' '203' '1']
 ['33' '147' '168' '1']
 ['63' '162' '171' '1']
 ['34' '142' '243' '1']
 ['74' '155' '255' '1']
 ['68' '148' '256' '1']
 ['37' '175' '379' '1']
 ['57' '176' '298' '1']
 ['32' '172' '206' '1']
 ['66' '174' '292' '1']
 ['59' '177' '263' '1']
 ['60' '177' '206' '1']
 ['40' '167' '163' '1']
 ['83' '217' '267' '1']
 ['82' '167' '214' '1']
 ['35' '174' '152' '1']
 ['41' '153' '220' '1']
 ['32' '141' '158' '1']
 ['51' '145' '168' '1']
 ['45' '179' '247' '1']
 ['45' '169' '294' '1']
 ['60' '157' '206' '1']
 ['38' '153' '193' '1']
 ['74' '153' '280' '1']
 ['72' '163' '152' '1']
 ['41' '

In [23]:
# Bệnh nhân có cholesterol > 240 : 
mask_cholesterol_a = np_hospital_a[1:,2].astype(int) > 240
print('Bệnh nhân có Cholesterol > 240: ','\n')
print(np_hospital_a[1:,][mask_cholesterol_a])

Bệnh nhân có Cholesterol > 240:  

[['82' '98' '285' '1']
 ['63' '171' '274' '1']
 ['39' '91' '330' '1']
 ['63' '90' '286' '1']
 ['83' '152' '293' '1']
 ['76' '149' '293' '1']
 ['40' '154' '245' '1']
 ['54' '148' '251' '1']
 ['46' '166' '263' '1']
 ['64' '149' '269' '1']
 ['38' '141' '268' '1']
 ['58' '125' '283' '1']
 ['39' '135' '264' '1']
 ['34' '142' '243' '1']
 ['74' '155' '255' '1']
 ['35' '92' '273' '1']
 ['68' '148' '256' '1']
 ['37' '175' '379' '1']
 ['57' '176' '298' '1']
 ['44' '91' '272' '1']
 ['66' '174' '292' '1']
 ['47' '129' '298' '1']
 ['59' '177' '263' '1']
 ['83' '217' '267' '1']
 ['79' '119' '286' '1']
 ['45' '179' '247' '1']
 ['76' '103' '262' '1']
 ['45' '169' '294' '1']
 ['74' '153' '280' '1']
 ['84' '116' '294' '1']
 ['41' '163' '295' '1']
 ['75' '172' '284' '1']
 ['70' '135' '299' '1']
 ['50' '153' '295' '1']
 ['77' '170' '244' '1']
 ['64' '120' '254' '1']
 ['33' '98' '244' '1']
 ['48' '93' '285' '1']
 ['79' '116' '293' '1']
 ['56' '143' '284' '1']
 ['37' '93' 

- Hospital_b: 

In [24]:
# Bệnh nhân có huyết áp > 140: 
mask_blood_pre_b = np_hospital_b[1:,1].astype(int) > 140

print('Bệnh nhân có huyết áp > 140: ','\n')
print(np_hospital_b[1:,:][mask_blood_pre_b])

Bệnh nhân có huyết áp > 140:  

[['55' '172' '203' '1']
 ['41' '143' '258' '1']
 ['68' '175' '221' '1']
 ['74' '143' '291' '1']
 ['34' '145' '349' '1']
 ['81' '168' '189' '1']
 ['33' '174' '239' '1']
 ['45' '141' '158' '1']
 ['74' '153' '224' '1']
 ['71' '173' '240' '1']
 ['40' '195' '200' '1']
 ['50' '142' '166' '1']
 ['57' '145' '161' '1']
 ['50' '156' '368' '1']
 ['55' '174' '253' '1']
 ['71' '173' '215' '1']
 ['69' '179' '270' '1']
 ['79' '166' '254' '1']
 ['59' '173' '239' '1']
 ['36' '168' '204' '1']
 ['55' '213' '164' '0']
 ['59' '143' '288' '1']
 ['31' '162' '178' '1']
 ['79' '173' '249' '1']
 ['73' '156' '187' '1']
 ['46' '172' '177' '1']
 ['66' '142' '287' '1']
 ['61' '147' '155' '1']
 ['84' '150' '195' '1']
 ['43' '176' '296' '1']
 ['39' '180' '277' '1']
 ['46' '144' '274' '1']
 ['79' '157' '239' '1']
 ['59' '171' '168' '1']
 ['83' '141' '160' '1']
 ['75' '208' '231' '1']
 ['72' '168' '281' '1']
 ['40' '175' '153' '1']
 ['58' '148' '291' '1']
 ['46' '154' '265' '1']
 ['62' '

In [25]:
# Bệnh nhân có cholesterol > 240 : 
mask_cholesterol_b = np_hospital_b[1:,2].astype(int) > 240
print('Bệnh nhân có Cholesterol > 240: ','\n')
print(np_hospital_b[1:,][mask_cholesterol_b])

Bệnh nhân có Cholesterol > 240:  

[['41' '143' '258' '1']
 ['32' '104' '250' '1']
 ['74' '143' '291' '1']
 ['65' '136' '260' '1']
 ['34' '145' '349' '1']
 ['42' '104' '266' '1']
 ['64' '128' '259' '1']
 ['50' '156' '368' '1']
 ['55' '174' '253' '1']
 ['44' '100' '273' '1']
 ['69' '179' '270' '1']
 ['79' '166' '254' '1']
 ['59' '143' '288' '1']
 ['45' '95' '293' '1']
 ['42' '120' '281' '1']
 ['48' '126' '260' '1']
 ['37' '138' '271' '1']
 ['79' '173' '249' '1']
 ['63' '121' '254' '1']
 ['67' '121' '277' '1']
 ['60' '131' '298' '1']
 ['62' '103' '292' '1']
 ['54' '135' '256' '1']
 ['37' '128' '289' '1']
 ['66' '142' '287' '1']
 ['50' '91' '255' '1']
 ['63' '106' '289' '1']
 ['43' '176' '296' '1']
 ['36' '103' '292' '1']
 ['44' '98' '279' '1']
 ['39' '180' '277' '1']
 ['46' '144' '274' '1']
 ['84' '107' '254' '1']
 ['52' '132' '259' '1']
 ['44' '131' '269' '1']
 ['67' '130' '244' '1']
 ['81' '126' '283' '1']
 ['61' '140' '242' '1']
 ['72' '168' '281' '1']
 ['48' '124' '281' '1']
 ['58' '

**Yêu cầu 6: Fancy indexing: top-10 bệnh nhân có BMI cao nhất.**

- Trong file csv của thầy k có chiều cao cân nặng nên em không tính được chỉ số BMI. Em xin phép bỏ qua yêu cầu này ạ

**Yêu cầu 7: Broadcasting: chuẩn hoá từng chỉ số (x - mean).** 

- Hospital_a: 

In [26]:

# Chuẩn hóa huyết áp: 
bool_pre_a = arr_blood_pre_a[1:].astype(float) - (arr_blood_pre_a[1:].astype(float)).mean()
np_bool_pre_a = np.array(bool_pre_a)
np.set_printoptions(precision=2, suppress=True)
print('Chuẩn hóa huyết áp: ','\n')
print(np_bool_pre_a)





Chuẩn hóa huyết áp:  

[ 11.01 -38.99 -31.99  34.01   8.01 -45.99 -37.99  13.01 -46.99 -32.99
  57.01  15.01  12.01 -26.99  17.01 -25.99 -17.99  20.01  11.01  29.01
  12.01   4.01 -38.99 -13.99 -22.99  70.01  41.01 -11.99  33.01  10.01
  25.01  -1.99   5.01  -2.99 -28.99  18.01 -21.99 -44.99  11.01 -30.99
  38.01  39.01  35.01 -13.99 -45.99  37.01  -7.99  40.01  40.01  30.01
  80.01 -11.99  30.01 -17.99 -31.99   3.01  37.01  16.01   4.01 -37.99
   8.01  42.01 -33.99   0.01  32.01  20.01  16.01  16.01 -14.99 -20.99
  26.01  26.01  31.01  35.01  -0.99  -1.99  25.01  11.01  16.01  25.01
  33.01 -16.99 -12.99 -38.99   5.01 -43.99  -4.99   2.01 -20.99   6.01
 -43.99 -43.99  27.01 -14.99 -35.99   0.01  22.01 -27.99   9.01 -38.99
 -41.99   1.01   2.01  10.01  18.01  41.01  -0.99 -17.99  25.01 -22.99
  -6.99 -39.99 -44.99  40.01  28.01  16.01  -9.99 -30.99 -32.99 -23.99
  74.01  17.01  12.01 -21.99  39.01  19.01   3.01   8.01  -8.99 -24.99
 -14.99  21.01 -45.99 -36.99 -42.99 -42.99  30.01  16.

In [27]:
# Chuẩn hóa Cholesterol: 
cholesterol_a = arr_cholesterol_a[1:].astype(float) - (arr_cholesterol_a[1:].astype(float)).mean()
np_cholesterol_a = np.array(cholesterol_a)
np.set_printoptions(precision=2, suppress=True)
print('Chuẩn hóa Cholesterol: ','\n')
print(np_cholesterol_a)

Chuẩn hóa Cholesterol:  

[-65.29  54.71  -4.29  43.71 -32.29  99.71 -22.29 -78.29  55.71 -66.29
 -32.29  62.71  62.71   5.71  14.71 -13.29 -36.29 -31.29  20.71  32.71
  38.71  37.71 -66.29  -6.29 -71.29   1.71 -14.29  52.71 -27.29 -62.29
 -59.29  33.71  12.71 -65.29 -67.29  24.71 -69.29  42.71  25.71 -68.29
 148.71  67.71 -24.29 -24.29  41.71  61.71  67.71  32.71 -24.29 -67.29
  36.71   3.71 -16.29  55.71 -63.29  -6.29 -78.29 -10.29 -72.29 -62.29
 -62.29  16.71  31.71   7.71  63.71 -24.29 -37.29  49.71 -46.29  63.71
 -78.29  64.71 -74.29  53.71  -1.29  68.71 -69.29   2.71  64.71  -2.29
  13.71  23.71 -12.29  13.71   7.71  54.71 -73.29 -38.29  62.71  53.71
  79.71  12.71 -38.29 -52.29 -10.29 -27.29   7.71 -68.29  65.71  67.71
  24.71  -0.29 -34.29  41.71  22.71 -56.29  56.71  42.71  61.71  28.71
  11.71 -17.29  59.71  49.71 -73.29 -76.29 -24.29  41.71  67.71 -57.29
   8.71 -23.29  64.71  45.71  45.71 -10.29 -18.29 -39.29 -72.29  49.71
  41.71  69.71  68.71   2.71  34.71  61.71  46.71 -

In [28]:
# Chuẩn hóa heart_risk: 
heart_risk_a = arr_heart_risk_a[1:].astype(float) - arr_heart_risk_a[1:].astype(float).mean()
np_heart_risk_a = np.array(heart_risk_a)
np.set_printoptions(precision=2, suppress=True)
print('Chuẩn hóa chỉ số Heart_risk: ','\n')
print(np_heart_risk_a)

Chuẩn hóa chỉ số Heart_risk:  

[ 0.21  0.21  0.21  0.21  0.21  0.21 -0.79  0.21  0.21 -0.79 -0.79  0.21
  0.21  0.21  0.21 -0.79 -0.79  0.21  0.21  0.21  0.21  0.21 -0.79  0.21
 -0.79  0.21  0.21  0.21  0.21  0.21  0.21  0.21  0.21 -0.79 -0.79  0.21
 -0.79  0.21  0.21 -0.79  0.21  0.21  0.21 -0.79  0.21  0.21  0.21  0.21
  0.21  0.21  0.21  0.21  0.21  0.21 -0.79  0.21  0.21  0.21  0.21 -0.79
  0.21  0.21  0.21  0.21  0.21  0.21  0.21  0.21 -0.79  0.21  0.21  0.21
  0.21  0.21  0.21  0.21  0.21  0.21  0.21  0.21  0.21  0.21 -0.79  0.21
  0.21  0.21 -0.79 -0.79  0.21  0.21 -0.79  0.21  0.21 -0.79 -0.79 -0.79
  0.21 -0.79  0.21  0.21  0.21  0.21 -0.79  0.21  0.21  0.21  0.21  0.21
  0.21  0.21  0.21 -0.79  0.21  0.21  0.21  0.21 -0.79  0.21  0.21 -0.79
  0.21  0.21  0.21  0.21  0.21  0.21 -0.79  0.21 -0.79  0.21  0.21  0.21
  0.21  0.21  0.21  0.21  0.21  0.21 -0.79 -0.79  0.21  0.21 -0.79  0.21
  0.21  0.21  0.21  0.21  0.21  0.21  0.21  0.21  0.21  0.21  0.21  0.21
 -0.79  0.21  0.21 

- Hospital_b: 

In [29]:

# Chuẩn hóa huyết áp: 
bool_pre_b = arr_blood_pre_b[1:].astype(float) - (arr_blood_pre_b[1:].astype(float)).mean()
np_bool_pre_b = np.array(bool_pre_b)
np.set_printoptions(precision=2, suppress=True)
print('Chuẩn hóa huyết áp: ','\n')
print(np_bool_pre_b)

Chuẩn hóa huyết áp:  

[ 38.63   9.63  -7.37  -1.37  41.63 -29.37   9.63   2.63  11.63 -41.37
  34.63  40.63   7.63  19.63  39.63  61.63 -29.37   8.63  11.63  -5.37
  22.63  40.63  39.63  -2.37 -33.37  45.63  32.63 -32.37  39.63  34.63
  79.63   9.63  -7.37 -38.37 -13.37  28.63 -43.37 -13.37  -7.37   4.63
  39.63 -12.37 -12.37  22.63  -2.37 -23.37  -2.37 -30.37 -27.37   1.63
  -5.37  38.63 -10.37   8.63  13.63 -42.37  16.63 -27.37  42.63 -30.37
  -6.37 -35.37  46.63   1.63  10.63 -37.37  23.63 -24.37  37.63 -25.37
 -26.37 -40.37  -1.37   7.63 -37.37  74.63  -2.37   3.63  -3.37  -7.37
   6.63 -29.37 -27.37  34.63  41.63  -9.37 -19.37  14.63  -6.37 -41.37
 -29.37  20.63  15.63 -41.37 -23.37 -22.37  16.63 -41.37 -34.37  28.63
 -27.37  15.63 -22.37 -34.37 -21.37  21.63  33.63  31.63  -7.37  16.63
 -25.37 -17.37  37.63 -42.37 -35.37 -24.37 -41.37 -27.37   8.63  -5.37
  36.63  30.63 -12.37 -20.37  -9.37   9.63 -19.37  12.63  -6.37   6.63
  -4.37 -16.37  41.63  25.63 -30.37  34.63   0.63  37.

In [30]:
# Chuẩn hóa Cholesterol: 
cholesterol_b = arr_cholesterol_b[1:].astype(float) - (arr_cholesterol_b[1:].astype(float)).mean()
np_cholesterol_b = np.array(cholesterol_b)
np.set_printoptions(precision=2, suppress=True)
print('Chuẩn hóa Cholesterol: ','\n')
print(np_cholesterol_b)

Chuẩn hóa Cholesterol:  

[-27.57  27.43 -35.57   4.43  -9.57  19.43  60.43  29.43 118.43 -75.57
 -41.57   8.43 -72.57  -6.57   9.43 -30.57  35.43 -64.57 -69.57  28.43
 137.43  22.43 -15.57 -43.57  42.43  39.43  23.43 -39.57   8.43 -26.57
 -66.57  57.43 -59.57  62.43 -13.57 -52.57   0.43  50.43  29.43  40.43
  18.43  23.43  46.43 -43.57  -7.57 -47.57  67.43  61.43 -74.57  25.43
  58.43 -53.57   4.43  56.43 -75.57  24.43 -35.57  58.43  65.43  61.43
  -9.57  48.43  46.43 -32.57  43.43 -74.57   8.43 -45.57 -62.57 -68.57
  23.43 -29.57  28.43 -70.57 -33.57   0.43  38.43 -32.57  13.43  52.43
  11.43 -45.57 -76.57  50.43 -77.57  50.43  -1.57  60.43  39.43  69.43
 -27.57  34.43 -20.57  -8.57  13.43  50.43  67.43  34.43 -17.57 -17.57
 137.43 -44.57 -63.57 -27.57 -37.57 -36.57 -45.57 -74.57 -77.57  67.43
 -16.57 -22.57  21.43 -47.57  61.43  37.43 -67.57 -17.57  51.43  61.43
 -10.57  11.43 -55.57  68.43 -45.57  60.43  16.43  10.43  -3.57 -45.57
 -54.57 -47.57 -52.57  36.43 -27.57 -71.57  64.43  

In [31]:
# Chuẩn hóa heart_risk: 
heart_risk_b = arr_heart_risk_b[1:].astype(float) - arr_heart_risk_b[1:].astype(float).mean()
np_heart_risk_b = np.array(heart_risk_b)
np.set_printoptions(precision=2, suppress=True)
print('Chuẩn hóa chỉ số Heart_risk: ','\n')
print(np_heart_risk_b)

Chuẩn hóa chỉ số Heart_risk:  

[ 0.24  0.24 -0.76  0.24  0.24  0.24  0.24  0.24  0.24 -0.76  0.24  0.24
  0.24  0.24  0.24  0.24  0.24  0.24  0.24  0.24  0.24  0.24  0.24 -0.76
  0.24  0.24  0.24 -0.76  0.24  0.24 -0.76  0.24 -0.76  0.24 -0.76  0.24
  0.24  0.24  0.24  0.24  0.24  0.24  0.24  0.24  0.24 -0.76  0.24  0.24
  0.24  0.24  0.24  0.24  0.24  0.24  0.24  0.24  0.24  0.24  0.24  0.24
  0.24  0.24  0.24 -0.76  0.24 -0.76  0.24 -0.76  0.24 -0.76  0.24 -0.76
  0.24  0.24 -0.76  0.24  0.24 -0.76  0.24  0.24  0.24 -0.76 -0.76  0.24
  0.24  0.24  0.24  0.24  0.24  0.24 -0.76  0.24  0.24  0.24  0.24  0.24
  0.24  0.24 -0.76  0.24  0.24  0.24 -0.76 -0.76 -0.76  0.24  0.24  0.24
 -0.76  0.24 -0.76 -0.76  0.24 -0.76  0.24  0.24 -0.76 -0.76  0.24  0.24
  0.24  0.24 -0.76  0.24 -0.76  0.24  0.24  0.24  0.24 -0.76 -0.76 -0.76
  0.24  0.24 -0.76  0.24  0.24  0.24  0.24  0.24 -0.76 -0.76  0.24  0.24
 -0.76  0.24  0.24  0.24  0.24  0.24  0.24 -0.76  0.24 -0.76  0.24  0.24
  0.24  0.24  0.24 

**Yêu cầu 8: np.diff: phân tích biến động huyết áp theo danh sách đã sắp xếp.**

- Hospital_a: 



In [32]:
# Phân tích biến động huyết áp: 
print('Biến động huyết áp: ','\n')
print(np.diff(np_bool_pre_a))

Biến động huyết áp:  

[-50.   7.  66. -26. -54.   8.  51. -60.  14.  90. -42.  -3. -39.  44.
 -43.   8.  38.  -9.  18. -17.  -8. -43.  25.  -9.  93. -29. -53.  45.
 -23.  15. -27.   7.  -8. -26.  47. -40. -23.  56. -42.  69.   1.  -4.
 -49. -32.  83. -45.  48.   0. -10.  50. -92.  42. -48. -14.  35.  34.
 -21. -12. -42.  46.  34. -76.  34.  32. -12.  -4.   0. -31.  -6.  47.
   0.   5.   4. -36.  -1.  27. -14.   5.   9.   8. -50.   4. -26.  44.
 -49.  39.   7. -23.  27. -50.   0.  71. -42. -21.  36.  22. -50.  37.
 -48.  -3.  43.   1.   8.   8.  23. -42. -17.  43. -48.  16. -33.  -5.
  85. -12. -12. -26. -21.  -2.   9.  98. -57.  -5. -34.  61. -20. -16.
   5. -17. -16.  10.  36. -67.   9.  -6.   0.  73. -14. -20. -34.  35.
  -1. -27.  23.  -3.  19.   2. -53.  30.  22. -11.  32. -18. -44.  -9.
  52. -56.  51.  32. -33. -17.  23. -17.   8.  36. -50.  52.  -6. -63.
 -12.   3.  -7.   6.  53. -55.  23.  47. -74.  71. -48. -14.  52.  -6.
  22. -13.   6. -47.  -9.  52.   5.  16. -52.  -4.  37

- Hospital_b: 

In [33]:
# Chuẩn hóa huyết áp: 
print('Chuẩn hóa huyết áp: ','\n')
print(np.diff(np_bool_pre_b))

Chuẩn hóa huyết áp:  

[-29. -17.   6.  43. -71.  39.  -7.   9. -53.  76.   6. -33.  12.  20.
  22. -91.  38.   3. -17.  28.  18.  -1. -42. -31.  79. -13. -65.  72.
  -5.  45. -70. -17. -31.  25.  42. -72.  30.   6.  12.  35. -52.   0.
  35. -25. -21.  21. -28.   3.  29.  -7.  44. -49.  19.   5. -56.  59.
 -44.  70. -73.  24. -29.  82. -45.   9. -48.  61. -48.  62. -63.  -1.
 -14.  39.   9. -45. 112. -77.   6.  -7.  -4.  14. -36.   2.  62.   7.
 -51. -10.  34. -21. -35.  12.  50.  -5. -57.  18.   1.  39. -58.   7.
  63. -56.  43. -38. -12.  13.  43.  12.  -2. -39.  24. -42.   8.  55.
 -80.   7.  11. -17.  14.  36. -14.  42.  -6. -43.  -8.  11.  19. -29.
  32. -19.  13. -11. -12.  58. -16. -56.  65. -34.  37.  -9. -34. -36.
  22.  25.   8. -34. -10.  62.  14. -42. -32.  10. -23.  80. -71.  41.
 -27.  25.   9.  16. -56. -18.  11.  69.  -2. -25.   0.   6. -44.  66.
 -44.  -4.  13. -43.  11.  51. -59.  47. -32.  13.  -9.]


**Yêu cầu 9: Tính mean, std, max, min cho từng chỉ số.** 

- Hospital_a: 

In [34]:
# Huyết áp: 
bool_pre_a_mean = arr_blood_pre_a[1:].astype(float).mean()
bool_pre_a_std = arr_blood_pre_a[1:].astype(float).std()
bool_pre_a_max = arr_blood_pre_a[1:].astype(float).max()
bool_pre_a_min = arr_blood_pre_a[1:].astype(float).min()

print('Chỉ số huyết áp: ','\n')
print(f'----Chỉ số Mean: {bool_pre_a_mean}')
print(f'----Chỉ số STD: {bool_pre_a_std:.2f}')
print(f'----Chỉ số Max: {bool_pre_a_max}')
print(f'----Chỉ số Min: {bool_pre_a_min}')



Chỉ số huyết áp:  

----Chỉ số Mean: 136.99
----Chỉ số STD: 28.13
----Chỉ số Max: 217.0
----Chỉ số Min: 90.0


In [35]:
# Cholesterol: 
cholesterol_a_mean = arr_cholesterol_a[1:].astype(float).mean()
cholesterol_a_std = arr_cholesterol_a[1:].astype(float).std()
cholesterol_a_max = arr_cholesterol_a[1:].astype(float).max()
cholesterol_a_min = arr_cholesterol_a[1:].astype(float).min()

print('Chỉ số Cholesterol: ','\n')
print(f'----Chỉ số Mean: {cholesterol_a_mean}')
print(f'----Chỉ số STD: {cholesterol_a_std:.2f}')
print(f'----Chỉ số Max: {cholesterol_a_max}')
print(f'----Chỉ số Min: {cholesterol_a_min}')




Chỉ số Cholesterol:  

----Chỉ số Mean: 230.29
----Chỉ số STD: 48.03
----Chỉ số Max: 379.0
----Chỉ số Min: 152.0


In [36]:
# Heart_risk: 
heart_risk_a_mean = arr_heart_risk_a[1:].astype(float).mean()
heart_risk_a_std = arr_heart_risk_a[1:].astype(float).std()
heart_risk_a_max = arr_heart_risk_a[1:].astype(float).max()
heart_risk_a_min = arr_heart_risk_a[1:].astype(float).min()


print('Chỉ số Heart_risk: ','\n')
print(f'----Chỉ số Mean: {heart_risk_a_mean}')
print(f'----Chỉ số STD: {heart_risk_a_std:.2f}')
print(f'----Chỉ số Max: {heart_risk_a_max}')
print(f'----Chỉ số Min: {heart_risk_a_min}')

Chỉ số Heart_risk:  

----Chỉ số Mean: 0.785
----Chỉ số STD: 0.41
----Chỉ số Max: 1.0
----Chỉ số Min: 0.0


- Hospital_b: 


In [37]:
# Huyết áp: 
bool_pre_b_mean = arr_blood_pre_b[1:].astype(float).mean()
bool_pre_b_std = arr_blood_pre_b[1:].astype(float).std()
bool_pre_b_max = arr_blood_pre_b[1:].astype(float).max()
bool_pre_b_min = arr_blood_pre_b[1:].astype(float).min()

print('Chỉ số huyết áp: ','\n')
print(f'----Chỉ số Mean: {bool_pre_b_mean:.2f}')
print(f'----Chỉ số STD: {bool_pre_b_std:.2f}')
print(f'----Chỉ số Max: {bool_pre_b_max}')
print(f'----Chỉ số Min: {bool_pre_b_min}')

Chỉ số huyết áp:  

----Chỉ số Mean: 133.37
----Chỉ số STD: 27.60
----Chỉ số Max: 213.0
----Chỉ số Min: 90.0


In [38]:
# Cholesterol: 
cholesterol_b_mean = arr_cholesterol_b[1:].astype(float).mean()
cholesterol_b_std = arr_cholesterol_b[1:].astype(float).std()
cholesterol_b_max = arr_cholesterol_b[1:].astype(float).max()
cholesterol_b_min = arr_cholesterol_b[1:].astype(float).min()

print('Chỉ số Cholesterol: ','\n')
print(f'----Chỉ số Mean: {cholesterol_b_mean:.2f}')
print(f'----Chỉ số STD: {cholesterol_b_std:.2f}')
print(f'----Chỉ số Max: {cholesterol_b_max}')
print(f'----Chỉ số Min: {cholesterol_b_min}')

Chỉ số Cholesterol:  

----Chỉ số Mean: 230.57
----Chỉ số STD: 47.44
----Chỉ số Max: 368.0
----Chỉ số Min: 153.0


In [40]:
# Heart_risk: 
heart_risk_b_mean = arr_heart_risk_b[1:].astype(float).mean()
heart_risk_b_std = arr_heart_risk_b[1:].astype(float).std()
heart_risk_b_max = arr_heart_risk_b[1:].astype(float).max()
heart_risk_b_min = arr_heart_risk_b[1:].astype(float).min()


print('Chỉ số Heart_risk: ','\n')
print(f'----Chỉ số Mean: {heart_risk_b_mean:.2f}')
print(f'----Chỉ số STD: {heart_risk_b_std:.2f}')
print(f'----Chỉ số Max: {heart_risk_b_max}')
print(f'----Chỉ số Min: {heart_risk_b_min}')

Chỉ số Heart_risk:  

----Chỉ số Mean: 0.76
----Chỉ số STD: 0.43
----Chỉ số Max: 1.0
----Chỉ số Min: 0.0
